sudo: required
services:
  - docker

before_install:
  - docker build -t docker_travis -f ./Dockerfile.dev .

script:
  - docker run -e CI=true docker_travis npm run test



deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-lco"
  env: "Dockerlco-env"
  bucket_name: "elasticbeanstalk-us-east-1-682162257160"
  bucket_path: "docker-lco"
  on:
    branch: master
